### ISSUE TITLE
[REQUEST] Sass Vars to JSON - Does not seem to support Boolean and List type values

### ISSUE THREAD

**Issue by classicmike** [devtin/sass-vars-to-json#1]
Hi @devtin,

Not sure if you are active on this repo anymore.

But I'm trying to export some variables out to JSON format for later use. Your library seems to do most of the conversion of the sass variables very nicely however, the following data types from sass-extract, don't actually convert:

- SassBoolean
- SassList

Any of these styles returns as undefined in the final JSON output.

Looking at the code, this plugin only covers 'SassMap', 'SassColor', 'SassString' and 'SassNumber'.

If you are not making update anymore,  I can see if I can do a fix for this via a fork.

Thanks.

**Comment by devtin** [comment]
Hi @classicmike,

Just merged you PR.

Thank you for the contribution!

**Comment by classicmike** [comment]
Hi @devtin 
Thanks for merging my PR.

A question on releasing, are you planning on doing a version bump so people can consume the changes from NPM?

Thanks

**Comment by devtin** [comment]
Just did! Sorry for the delay!

**Comment by classicmike** [comment]
@devtin - Thanks for the release. :)
